version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/financial_dashboard
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    volumes:
      - ./backend:/app:Z
      - ~/.m2:/root/.m2:Z

  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
    ports:
      - "8081:8080"
    volumes:
      - ./frontend:/app:Z
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=financial_dashboard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z

volumes:
  postgres_data: 